Cherry Pick PR to PROD-120
topcoder-platform/mfe-customer-work pull request #447
Opened 2022-06-09 06:42 UTC by dedywahyudi

Cherry Pick from these PR:

https://github.com/topcoder-platform/mfe-customer-work/pull/436/commits
https://github.com/topcoder-platform/mfe-customer-work/pull/435/commits

2022-06-09 14:40 UTC, brooketopcoder requested changes
thanks for knocking this out, @dedywahyudi !

we just need to narrow the scope of the changes to only the items that will be in the current release. 

https://topcoder.atlassian.net/browse/PROD-2144

The website design v2 and problem & data advisory changes are in the following release:

https://topcoder.atlassian.net/browse/PROD-2145

2022-06-10 10:59 UTC, dedywahyudi commented
@brooketopcoder 

Can we ignore this PR. There are some conflicts that not merged correctly on this PR.
I created new PR by cherry pick from previous PR and all commits you made on "clone-PROD-120" branch: 
https://github.com/topcoder-platform/mfe-customer-work/pull/454

2022-06-10 11:01 UTC, dedywahyudi commented
I'll reply all feedback above.
But, please check another PR for the fixes: https://github.com/topcoder-platform/mfe-customer-work/pull/454

2022-06-10 11:03 UTC, dedywahyudi commented on src/routes/Products/components/BasicInfo/index.jsx
> +    description: { title: "Description", option: "", value: "" },
@brooketopcoder After new PR this should be fixed.

2022-06-10 11:04 UTC, dedywahyudi commented on src/components/Banners/FeaturedWorkTypeBanner/styles.module.scss
> +  &.problem-statement--data-advisory,
@brooketopcoder This should be fixed too

2022-06-10 11:04 UTC, dedywahyudi commented on src/components/Banners/FeaturedWorkTypeBanner/styles.module.scss
> +    &.problem-statement--data-advisory,
@brooketopcoder This should be fixed too

2022-06-10 11:30 UTC, dedywahyudi commented on src/routes/Products/components/BasicInfo/index.jsx
> +  } else if (isDataAdvisory) {
@brooketopcoder Done, this is removed

2022-06-10 11:30 UTC, dedywahyudi commented on src/routes/Products/components/BasicInfo/index.jsx
> +    if (basicInfo && basicInfo?.projectTitle?.value.length > 0) {
@brooketopcoder cool, this is fixed now.

2022-06-10 11:31 UTC, dedywahyudi commented on src/routes/Products/components/BasicInfoForm/index.jsx
> +import ColorOptions from "../../../Branding/components/ColorOptions";
@brooketopcoder ok, i think this is fixed too

2022-06-10 11:34 UTC, closed without merging